DocflowApp/DocflowApp/Models/EntityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DocflowApp.Models
{
    public abstract class EntityViewModel<T>
    {
        public T Entity { get; set; }
    }
}

DocflowApp/DocflowApp/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DocflowApp.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }
    }
}

DocflowApp/DocflowApp/Models/SortLinkModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Routing;

namespace DocflowApp.Models
{
    public class SortLinkModel
    {
        public string ActionName { get; set; }

        public string ControllerName { get; set; }

        public RouteValueDictionary RouteValues { get; set; }

        public string LinkText { get; set; }

        public System.Web.UI.WebControls.SortDirection? SortDirection { get; set; }
    }
}

DocflowApp/DocflowApp/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DocflowApp.Models
{
    public class UserViewModel: EntityViewModel<User>
    {
        [DataType(DataType.Password)]
        [Required]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Required]
        [Compare("Password")]
        [Display(Name = "Подтвердите пароль")]
        public string ConfirmPassword { get; set; }
    }
}

DocflowApp/DocflowApp/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocflowApp.Files;
using DocflowApp.Models;
using DocflowApp.Models.Repositories;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace DocflowApp.Controllers
{
    public class AccountController : BaseController
    {
        public AccountController(UserRepository userRepository, IFileProvider[] fileProviders) 
            : base(userRepository, fileProviders)
        {
        }

        public ActionResult CreateUser(string login, string password)
        {
            var res = UserManager.CreateAsync(new User { UserName = login }, password);
            if (res.Result == IdentityResult.Success)
            {
                return RedirectToAction("Login");
            }
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {
            return View(new LoginViewModel { Date = DateTime.Now });
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = SignInManager.PasswordSignInAsync(model.UserName, model.Password, false, false);
                if (result.Result == SignInStatus.Success)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Неверный логин или пароль");
                }
            }
            return View(model);
        }
    }
}

DocflowApp/DocflowApp/Controllers/BaseController.cs
using DocflowApp.Files;
using DocflowApp.Models;
using DocflowApp.Models.Repositories;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocflowApp.Controllers
{
    public class BaseController : Controller
    {
        protected UserRepository userRepository;
        protected IFileProvider[] fileProviders;

        public BaseController(UserRepository userRepository, IFileProvider[] fileProviders)
        {
            this.userRepository = userRepository;
            this.fileProviders = fileProviders;
        }

        public SignInManager SignInManager
        {
            get { return HttpContext.GetOwinContext().Get<SignInManager>(); }
        }

        public UserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<UserManager>(); }
        }

        public User CurrentUser
        {
            get { return userRepository.GetCurrentUser(User); }
        }

        public IFileProvider GetFileProvider()
        {
            var key = ConfigurationManager.AppSettings["FileProvider"];
            return fileProviders.First(p => p.Name == key);
        }
    }
}

DocflowApp/DocflowApp/Controllers/BinaryFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocflowApp.Files;
using DocflowApp.Models.Repositories;

namespace DocflowApp.Controllers
{
    [Authorize]
    public class BinaryFileController : BaseController
    {
        private BinaryFileRepository binaryFileRepository;

        public BinaryFileController(UserRepository userRepository, IFileProvider[] fileProviders, BinaryFileRepository binaryFileRepository) 
            : base(userRepository, fileProviders)
        {
            this.binaryFileRepository = binaryFileRepository;
        }

        public ActionResult Download(long id)
        {
            var binaryFile = binaryFileRepository.Load(id);
            var stream = GetFileProvider().Load(binaryFile);
            return File(stream, binaryFile.ContentType);
        }
    }
}

DocflowApp/DocflowApp/Controllers/HomeController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocflowApp.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public HomeController(ISession session)
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DocflowApp/DocflowApp/Controllers/UserController.cs
using DocflowApp.Files;
using DocflowApp.Models;
using DocflowApp.Models.Filters;
using DocflowApp.Models.Repositories;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocflowApp.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {        
        public UserController(UserRepository userRepository, IFileProvider[] fileProviders) : 
            base(userRepository, fileProviders)
        {
            this.userRepository = userRepository;
        }

        // GET: User
        public ActionResult Index(UserFilter userFilter, FetchOptions options)
        {
            var users = userRepository.Find(userFilter, options);
            return View(users);
        }

        public ActionResult Create()
        {
            var model = new UserViewModel { Entity = new User() };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var res = UserManager.CreateAsync(model.Entity, model.Password);
                if (res.Result == IdentityResult.Success)
                {
                    GetFileProvider().Save(model.Entity.Avatar);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        public ActionResult Info(long id)
        {
            var user = userRepository.Load(id);
            return View(new UserViewModel { Entity = user });
        }

    }
}

DocflowApp/DocflowApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DocflowApp/DocflowApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DocflowApp/DocflowApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DocflowApp/DocflowApp/Views/Shared/DisplayTemplates/BinaryFile.cshtml
@using DocflowApp.Extensions
@model DocflowApp.Models.BinaryFile

@if (Model != null)
{
    var width = ViewData["width"];
    if (Html.IsImage(Model))
    {       
       <img alt="" src="@Url.Action("Download", "BinaryFile", new { id = Model.Id }, null)" style="@(width != null ? "width:" + width : "")" />
    }
    else
    {
        @Html.ActionLink(Model.Name, "Download", "BinaryFile", new { id = Model.Id }, new { style = width != null ? "width:" + width : "" })
    }
}

DocflowApp/DocflowApp/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime?

@(Model.HasValue ? Model.Value.ToString("d") : "Дата не задана")

DocflowApp/DocflowApp/Views/Shared/DisplayTemplates/User.cshtml
@model DocflowApp.Models.User

@if (Model != null)
{
    @(!string.IsNullOrWhiteSpace(Model.FIO) ? Model.FIO : Model.UserName)
}

DocflowApp/DocflowApp/Views/Shared/EditorTemplates/BinaryFile.cshtml
@model DocflowApp.Models.BinaryFile

<input type="file" name="@ViewData.TemplateInfo.GetFullHtmlFieldName("PostedFile")" />

DocflowApp/DocflowApp/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

<input type="text" class="form-control text-box single-line datepicker" name="@ViewData.TemplateInfo.GetFullHtmlFieldName("")" value="@(Model.HasValue ? Model.Value.ToString("d") : "")" />

DocflowApp/DocflowApp/Views/Shared/SortLink.cshtml
@model DocflowApp.Models.SortLinkModel

<a href="@Url.Action(Model.ActionName, Model.ControllerName, Model.RouteValues)">
    @Model.LinkText
    @if (Model.SortDirection.HasValue)
    {
        if (Model.SortDirection.Value == System.Web.UI.WebControls.SortDirection.Ascending)
        {
            <img src="~/Content/images/up.png" />
        }
        else
        {
            <img src="~/Content/images/down.png" />
        }
    }
</a>

DocflowApp/DocflowApp/Views/Shared/_Layout.cshtml
@using DocflowApp.Controllers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Документооборот</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Документооборот", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Пользователи", "Index", "User")</li>
                
                @{ 
                    var controller = ViewContext.Controller as BaseController;
                    if (controller != null && controller.CurrentUser != null)
                    {
                        <li>
                            <a href="#">#@controller.CurrentUser.UserName</a>
                        </li>
                    }
                }   
                 </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Документооборот</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DocflowApp/DocflowApp/Views/User/Create.cshtml
@model DocflowApp.Models.UserViewModel

@{
    ViewBag.Title = "Создание пользователя";
}

<h2>Новый пользователь</h2>

@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Entity.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entity.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Entity.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Entity.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entity.FIO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Entity.FIO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Entity.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Entity.Avatar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Entity.Avatar, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Создать" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("К списку", "Index")
</div>

DocflowApp/DocflowApp/Views/User/Filter.cshtml
@model DocflowApp.Models.Filters.UserFilter

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">

    <div class="form-group">       
        <div class="col-md-10">
            <table style="width: 100%;">
                <tr>
                    <td> 
                        @Html.EditorFor(model => model.SearchString, new { htmlAttributes = new { @class = "form-control", style = "max-width:none;" } })
                    </td>
                    <td style="width: 50px;">
                        <div class="col-md-offset-2 col-md-10" style="margin-left: 0px;">
                            <input type="submit" value="Найти" class="btn btn-default" />
                        </div>                        
                    </td>
                    <td style="width: 150px;">
                        <div>
                            <a href="#" onclick="toggleFields()">Расширенный поиск</a>
                        </div>
                    </td>
                </tr>
            </table>           
        </div>
    </div>
    <div id="ExtentedUserFilterFields" style="display: none;">
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Найти" class="btn btn-default" />
            </div>
        </div>
    </div>

   
</div>
}

<script type="text/javascript">
    function toggleFields() {
        if ($('#ExtentedUserFilterFields').is(':visible')) {
            $('#ExtentedUserFilterFields').hide('slow');
        }
        else {
            $('#ExtentedUserFilterFields').show('slow');
        }
    }
</script>

DocflowApp/DocflowApp/Views/User/Index.cshtml
@using DocflowApp.Extensions
@using DocflowApp.Models.Filters
@model IEnumerable<DocflowApp.Models.User>

@{
    ViewBag.Title = "Пользователи";
}

<h2>Пользователи</h2>
<div>
    @Html.Partial("Filter", new UserFilter())
</div>
<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <tr>       
        <th>
            @Html.SortLink("Логин", "UserName", "Index", "User", null)
        </th>
        <th>
            @Html.SortLink("ФИО", "FIO", "Index", "User", null)
        </th>
        <th>
            @Html.SortLink("Дата приема", "WorkStartDate", "Index", "User", null)
        </th>
        <th>
            Автор
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>         
            @Html.ActionLink(item.UserName, "Info", "User", new { id = item.Id }, null)         
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorkStartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationAuthor)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id=item.Id }) |         
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

DocflowApp/DocflowApp/Views/User/Info.cshtml
@model DocflowApp.Models.UserViewModel

@{
    ViewBag.Title = Model.Entity.UserName;
}

<h2></h2>

<div>
    <h4>@(!string.IsNullOrEmpty(Model.Entity.FIO) ? Model.Entity.FIO : Model.Entity.UserName)</h4>
    <hr />
    <table>
        <tr>
            <td style="width:100px;">
                @Html.DisplayFor(m => m.Entity.Avatar, new { width = "96px" })
            </td>
            <td>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Entity.UserName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Entity.UserName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Entity.FIO)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Entity.FIO)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Entity.WorkStartDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Entity.WorkStartDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Entity.CreationAuthor)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Entity.CreationAuthor)
                    </dd>

                </dl>
            </td>
        </tr>
    </table>
    
</div>
<p>
   @Html.ActionLink("Назад к списку", "Index")
</p>